baseURL: https://nationalteam.github.io/notes/
languageCode: zh-tw
title: 國手筆記
theme: PaperMod

menu:
  main:
    - identifier: posts
      name: Posts
      url: "/"
      weight: 1
    - identifier: archives
      name: Archive
      url: "/archives/"
      weight: 2
    - identifier: search
      name: Search
      url: "/search/"
      weight: 3
    - identifier: tags
      name: Tags
      url: "/tags/"
      weight: 4

taxonomies:
  category: categories
  tag: tags

# https://github.com/adityatelange/hugo-PaperMod/wiki/Features#search-page
outputs:
  home:
    - html
    - rss
    - json

# https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-variables/
params:
  ShowShareButtons: "true"
  ShowReadingTime: "true"
  ShowPostNavLinks: "true"
  ShowCodeCopyButtons: "true"

sitemap:
  changefreq: "monthly"
  filename: "sitemap.xml"
  priority: "0.5"
