baseURL: https://nationalteam.github.io/notes/
languageCode: zh-tw
title: 國手筆記
theme: PaperMod

menu:
  main:
    - identifier: posts
      name: Posts
      url: "/"
      weight: 1
    - identifier: archives
      name: Archive
      url: "/archives/"
      weight: 2
    - identifier: search
      name: Search
      url: "/search/"
      weight: 3
    - identifier: tags
      name: Tags
      url: "/tags/"
      weight: 4
